class CommonPatterns:
    patterns = {
        "doğumyeri": [
            "{name} nerede doğmuştur?",
            "{name} nerede doğdu",
            "{name} doğum yeri",
            "{name}'{_suffix1} doğum yeri",
            "{name} doğum yeri neresi",
            "{name}'{_suffix1} doğum yeri neresi",
            "{name}'{_suffix1} doğum yeri neresidir",
            "{name} doğum yeri neresidir",
            "{name} nereli",
            "{name} memleketi",
            "{name}'{_suffix1} memleketi",
            "{name} memleketi nedir",
            "{name}'{_suffix1} memleketi nedir",
            "{name} doğduğu yer",
            "{name}'{_suffix1} doğduğu yer",
            "{name} doğduğu yer neresidir",
            "{name}'{_suffix1} doğduğu yer neresidir",
            "{name} doğduğu yer neresi",
            "{name}'{_suffix1} doğduğu yer neresi",
            "{name} doğduğu il",
            "{name}'{_suffix1} doğduğu il",
            "{name} hangi ilde doğdu",
            "{name} hangi ülkede doğdu",
            "{name} doğduğu ülke",
            "{name}'{_suffix1} doğduğu ülke"
        ],
        "doğumtarihi": [
            "{name}'{_suffix1} doğum tarihi",
            "{name}'{_suffix1} doğum tarihi nedir",
            "{name}'{_suffix1} doğum tarihi ne zaman",
            "{name}'{_suffix1} doğum yılı",
            "{name}'{_suffix1} doğum yılı nedir",
            "{name}'{_suffix1} doğum yılı ne zaman",
            "{name}'{_suffix1} doğum günü ne zaman",
            "{name}'{_suffix1} doğum günü nedir",
            "{name} doğum tarihi",
            "{name} doğum tarihi nedir",
            "{name} doğum tarihi ne zaman",
            "{name} doğum yılı",
            "{name} doğum yılı nedir",
            "{name} doğum yılı ne zaman",
            "{name} doğum günü ne zaman",
            "{name} doğum günü nedir",
            "{name} ne zaman doğmuştur?",
            "{name} ne zaman doğdu",
            "{name} doğum zamanı"
        ],
        "ölümyeri": [
            "{name} nerede ölmüştür",
            "{name} nerede öldü",
            "{name} ölüm yeri",
            "{name}'{_suffix1} ölüm yeri",
            "{name} ölüm yeri neresi",
            "{name}'{_suffix1} ölüm yeri neresi",
            "{name}'{_suffix1} ölüm yeri neresidir",
            "{name} ölüm yeri neresidir",
            "{name} öldüğü yer",
            "{name}'{_suffix1} öldüğü yer",
            "{name} öldüğü yer neresidir",
            "{name}'{_suffix1} öldüğü yer neresidir",
            "{name} öldüğü yer neresi",
            "{name}'{_suffix1} ölüdüğü yer neresi",
            "{name} doğduğu il",
            "{name}'{_suffix1} ölüdüğü il",
            "{name} hangi ilde öldü",
            "{name} hangi ülkede öldü",
            "{name} öldüğü ülke",
            "{name}'{_suffix1} öldüğü ülke"
        ],
        "ölümtarihi": [
            "{name}'{_suffix1} ölüm tarihi",
            "{name}'{_suffix1} ölüm tarihi nedir",
            "{name}'{_suffix1} ölüm tarihi ne zaman",
            "{name}'{_suffix1} ölüm yılı",
            "{name}'{_suffix1} ölüm yılı nedir",
            "{name}'{_suffix1} ölüm yılı ne zaman",
            "{name}'{_suffix1} ölüm günü ne zaman",
            "{name}'{_suffix1} ölüm günü nedir",
            "{name} ölüm tarihi",
            "{name} ölüm tarihi nedir",
            "{name} ölüm tarihi ne zaman",
            "{name} ölüm yılı",
            "{name} ölüm yılı nedir",
            "{name} ölüm yılı ne zaman",
            "{name} ölüm günü ne zaman",
            "{name} ölüm günü nedir",
            "{name} ne zaman ölmüştür",
            "{name} ne zaman ölüm",
            "{name} ölüm zamanı",
            "{name}'{_suffix1} ölüm zamanı"
            ]
}
