class QuestionPatterns:
    patterns = {
        "Asker": {
            "rütbesi": [
                "{name} hangi rütbede görev yapmaktaydı?",
                "{name}'{~}n rütbesi nedir?",
                "{name}'{~}n rütbesi",
                "{name}'{~}n rütbesi neydi?",
                "{name} rütbe",
                "{name} hangi rütbeye sahiptir?"
            ],
            "doğumyeri": [
                "{name} nerede doğmuştur?",
                "{name} nerede doğdu",
                "{name} doğum yeri",
                "{name}'{~}n doğum yeri",
                "{name} doğum yeri neresi",
                "{name}'{~}n doğum yeri neresi",
                "{name}'{~}n doğum yeri neresidir",
                "{name} doğum yeri neresidir",
                "{name} nereli",
                "{name} memleketi",
                "{name}'{~}n memleketi",
                "{name} memleketi nedir",
                "{name}'{~}n memleketi nedir",
                "{name} doğduğu yer",
                "{name}'{~}n doğduğu yer",
                "{name} doğduğu yer neresidir",
                "{name}'{~}n doğduğu yer neresidir",
                "{name} doğduğu yer neresi",
                "{name}'{~}n doğduğu yer neresi",
                "{name} doğduğu il",
                "{name}'{~}n doğduğu il",
                "{name} hangi ilde doğdu",
                "{name} hangi ülkede doğdu",
                "{name} doğduğu ülke",
                "{name}'{~}n doğduğu ülke"
            ],
            "doğumtarihi": [
                "{name}'{~}n doğum tarihi",
                "{name}'{~}n doğum tarihi nedir",
                "{name}'{~}n doğum tarihi ne zaman",
                "{name}'{~}n doğum yılı",
                "{name}'{~}n doğum yılı nedir",
                "{name}'{~}n doğum yılı ne zaman",
                "{name}'{~}n doğum günü ne zaman",
                "{name}'{~}n doğum günü nedir",
                "{name} doğum tarihi",
                "{name} doğum tarihi nedir",
                "{name} doğum tarihi ne zaman",
                "{name} doğum yılı",
                "{name} doğum yılı nedir",
                "{name} doğum yılı ne zaman",
                "{name} doğum günü ne zaman",
                "{name} doğum günü nedir",
                "{name} ne zaman doğmuştur?",
                "{name} ne zaman doğdu",
                "{name} doğum zamanı"
            ],
            "hizmetyılları": [
                "{name}'{~}n hizmet yılları",
                "{name}'{~}n hizmet yılları nedir",
                "{name}'{~}n hizmet yılları ne zaman",
                "{name}'{~}n hizmet yılları ne zamandır",
                "{name}'{~}n ordudaki yılları",
                "{name}'{~}n ordudaki yılları nedir",
                "{name}'{~}n orduda geçirdiği yılları",
                "{name}'{~}n orduda geçirdiği yıllar",
                "{name} hizmet yılları",
                "{name} hizmet yılları nedir",
                "{name} hizmet yılları ne zaman",
                "{name} hizmet yılları ne zamandır",
                "{name} ordudaki yılları",
                "{name} ordudaki yılları nedir",
                "{name} orduda geçirdiği yılları",
                "{name} orduda geçirdiği yıllar",
                "{name} ne zaman hizmet vermiştir",
                "{name} ne zamanlar hizmet vermiştir",
                "{name} ne zaman hizmet vermişti",
                "{name} ne zamanlar hizmet vermişti",
                "{name} ne zaman askerdi",
                "{name} ne zaman asker olarak görev yapmıştır",
                "{name} ne zaman hizmet vermiştir",
                "{name} orduda geçirdiği yıllar",
                "{name} hangi yıllarını orduda geçirdi",
                "{name} hangi yıllarda ordudaydı",
                "{name} hangi yıllarda askerdi",
                "{name} hangi yıllarda arasında askerdi",
                "{name} hizmet dönemi",
                "{name} askerlik dönemi",
                "{name} ordu dönemi",
                "{name} ordudaki dönemi",
                "{name} ne zaman ordudaydı"
            ],
            "bağlılığı": [
                "{name} hangi ordudaydı",
                "{name} hangi orduda görev aldı",
                "{name} hangi orduya bağlı",
                "{name} hangi orduya bağlıydı",
                "{name} hangi orduya bağlıdır",
                "{name} hangi orduya bağlı görev aldı",
                "{name} hangi orduya bağlı görev almıştır",
                "{name} hangi ülke ordusundadır",
                "{name} hangi ülke ordusundaydı",
                "{name} hangi ülkenin ordusundaydı"
            ],
            "ölümyeri": [
                "{name} nerede ölmüştür",
                "{name} nerede öldü",
                "{name} ölüm yeri",
                "{name}'{~}n ölüm yeri",
                "{name} ölüm yeri neresi",
                "{name}'{~}n ölüm yeri neresi",
                "{name}'{~}n ölüm yeri neresidir",
                "{name} ölüm yeri neresidir",
                "{name} öldüğü yer",
                "{name}'{~}n öldüğü yer",
                "{name} öldüğü yer neresidir",
                "{name}'{~}n öldüğü yer neresidir",
                "{name} öldüğü yer neresi",
                "{name}'{~}n ölüdüğü yer neresi",
                "{name} doğduğu il",
                "{name}'{~}n ölüdüğü il",
                "{name} hangi ilde öldü",
                "{name} hangi ülkede öldü",
                "{name} öldüğü ülke",
                "{name}'{~}n öldüğü ülke"
            ],
            "savaşları": [
                "{name} nerede savaştı",
                "{name} nerelerde savaştı",
                "{name} hangi cephelerde savaştı",
                "{name} hangi savaşlarda savaştı",
                "{name} hangi savaşlarda vardı",
                "{name} hangi savaşlardaydı",
                "{name} hangi savaşlara katıldı",
                "{name}'{~}n katıldığı savaşlar",
                "{name} katıldığı savaşlar",
                "{name} bulunduğu savaşlar",
                "{name}'{~}n bulunduğu savaşlar",
                "{name} savaşlar",
                "{name}'{~}n savaşlar",
                "{name} savaşları",
                "{name}'{~}n savaşları",
                "{name} savaştığı yerler",
                "{name}'{~}n savaştığı yerler",
                "{name}'{~}n savaştığı yerler neresi",
                "{name}'{~}n savaştığı yerler hangiler",
                "{name}'{~}n savaştığı yerler hangileridir",
                "{name}'{~}n savaştığı yerler hangileriydi",
                "{name}'{~}n savaştığı yer hangileriydi",
                "{name}'{~}n savaştığı yer hangileri"
            ],
            "ölümtarihi": [
                "{name}'{~}n ölüm tarihi",
                "{name}'{~}n ölüm tarihi nedir",
                "{name}'{~}n ölüm tarihi ne zaman",
                "{name}'{~}n ölüm yılı",
                "{name}'{~}n ölüm yılı nedir",
                "{name}'{~}n ölüm yılı ne zaman",
                "{name}'{~}n ölüm günü ne zaman",
                "{name}'{~}n ölüm günü nedir",
                "{name} ölüm tarihi",
                "{name} ölüm tarihi nedir",
                "{name} ölüm tarihi ne zaman",
                "{name} ölüm yılı",
                "{name} ölüm yılı nedir",
                "{name} ölüm yılı ne zaman",
                "{name} ölüm günü ne zaman",
                "{name} ölüm günü nedir",
                "{name} ne zaman ölmüştür",
                "{name} ne zaman ölüm",
                "{name} ölüm zamanı",
                "{name}'{~}n ölüm zamanı"
            ],
            "komutaettikleri": [
                "{name}'{~}n komuta ettikleri",
                "{name} komuta ettikleri",
                "{name} kimleri komuta etti",
                "{name} kimleri komuta etmiştir",
                "{name} altındaki askerler",
                "{name} komuta altındaki askerler",
                "{name}'{~}n komutası altındaki askerler",
                "{name} altındaki askerler"
            ],
            "madalya": [
                "{name} hangi madalyalara sahiptir?",
                "{name} hangi madalyaları almıştır?",
                "{name} aldığı madalyalar",
                "{name} sahip olduğu madalyalar nelerdir?",
                "{name}'{#} takdim edilen madalyalar nelerdir?",
                "{name}'{#} verilen madalyalar nelerdir?",
                "{name}'{~}n kazandığı madalyalar nelerdir?",
                "{name}'{~}n sahip olduğu madalyalar nelerdir?"
            ]
        },
        "Basketbolcu": {
            "pozisyon": [
                "{name} hangi pozisyonda oynamaktadır?",
                "{name} hangi pozisyonda oynar?",
                "{name} hangi pozisyonda oynuyor?",
                "{name} hangi mevkiide oynamaktadır?",
                "{name} hangi mevkiide oynar?",
                "{name} hangi mevkiide oynuyor?",
                "{name}'{~}n oynadığı pozisyon nedir?",
                "{name}'{~}n oynamakta olduğu pozisyon nedir?",
                "{name}'{~}n pozisyonu nedir?",
                "{name}'{~}n oyun pozisyonu nedir?",
                "{name}'{~}n maçlardaki pozisyonu nedir?"
            ],
            "doğumtarihi": [
                "{name}'{~}n doğum tarihi",
                "{name}'{~}n doğum tarihi nedir",
                "{name}'{~}n doğum tarihi ne zaman",
                "{name}'{~}n doğum yılı",
                "{name}'{~}n doğum yılı nedir",
                "{name}'{~}n doğum yılı ne zaman",
                "{name}'{~}n doğum günü ne zaman",
                "{name}'{~}n doğum günü nedir",
                "{name} doğum tarihi",
                "{name} doğum tarihi nedir",
                "{name} doğum tarihi ne zaman",
                "{name} doğum yılı",
                "{name} doğum yılı nedir",
                "{name} doğum yılı ne zaman",
                "{name} doğum günü ne zaman",
                "{name} doğum günü nedir",
                "{name} ne zaman doğmuştur?",
                "{name} ne zaman doğdu",
                "{name} doğum zamanı"
            ],
            "doğumyeri": [
                "{name} nerede doğmuştur?",
                "{name} nerede doğdu",
                "{name} doğum yeri",
                "{name}'{~}n doğum yeri",
                "{name} doğum yeri neresi",
                "{name}'{~}n doğum yeri neresi",
                "{name}'{~}n doğum yeri neresidir",
                "{name} doğum yeri neresidir",
                "{name} nereli",
                "{name} memleketi",
                "{name}'{~}n memleketi",
                "{name} memleketi nedir",
                "{name}'{~}n memleketi nedir",
                "{name} doğduğu yer",
                "{name}'{~}n doğduğu yer",
                "{name} doğduğu yer neresidir",
                "{name}'{~}n doğduğu yer neresidir",
                "{name} doğduğu yer neresi",
                "{name}'{~}n doğduğu yer neresi",
                "{name} doğduğu il",
                "{name}'{~}n doğduğu il",
                "{name} hangi ilde doğdu",
                "{name} hangi ülkede doğdu",
                "{name} doğduğu ülke",
                "{name}'{~}n doğduğu ülke"
            ],
            "takım1": [
                "{name}'{~}n ilk oynadığı takım hangisidir?",
                "{name}'{~}n oynadığı ilk takım hangisidir?",
                "{name}'{~}n ilk takımı hangisi?",
                "{name}'{~}n ilk takımı hangisidir?",
                "{name}'{~}n kariyerine başladığı takım hangisidir?",
                "{name}'{~}n kariyerindeki ilk takım hangisidir?",
                "{name} profesyonel kariyerine hangi takımda başlamıştır?",
                "{name} profesyonel kariyerine hangi takımla başlamıştır?",
                "{name} profesyonel kariyerine hangi takımla adım atmıştır?",
                "{name}'{~}n profesyonel kariyerindeki ilk takım hangisidir?",
                "{name}'{~}n profesyonel kariyerindeki ilk takım hangisiydi?",
                "{name}'{~}n profesyonel kariyerindeki ilk takım hangisi?",
                "{name}'{~}n profesyonel kariyerindeki ilk takım neydi?",
                "{name}'{~}n profesyonel kariyerindeki ilk takım nedir?"
            ],
            "takımyıl1": [
                "{name} profesyonel kariyerine ne zaman başlamıştır?",
                "{name}'{~}n profesyonel kariyerine başlangıcı ne zamandır?",
                "{name}'{~}n profesyonel kariyerine başlangıcı ne zamandı",
                "{name}'{~}n profesyonel kariyerine başlangıcı ne zaman",
                "{name}'{~}n profesyonel kariyerine başlangıcı ne zaman oldu?",
                "{name}'{~}n profesyonel kariyerine başlangıcı ne zaman olmuştur?",
                "{name} profesyonel kariyerine hangi yılda başladı?",
                "{name} profesyonel kariyerine hangi yılda başlamıştı?",
                "{name} profesyonel kariyerine hangi yılda başlamıştır?",
                "{name} profesyonel kariyerine ne zaman başladı?",
                "{name} profesyonel kariyerine ne zaman başlamıştı?",
                "{name} profesyonel kariyerine ne zaman başlamıştır?",
                "{name}'{~}n ilk takımında ne zaman oynamıştır?",
                "{name}'{~}n ilk takımında ne zamanlar oynamıştır?",
                "{name}'{~}n ilk takımında hangi yıllar oynamıştır?",
                "{name}'{~}n ilk takımında hangi yıllar oynadı?",
                "{name}'{~}n ilk takımında oynadığı zaman aralığı nedir?",
                "{name}'{~}n ilk takımında oynadığı zaman aralığı nedir?",
                "{name}'{~}n ilk oynadığı takımda ne zaman oynamıştır?",
                "{name}'{~}n ilk oynadığı takımda hangi yıllar arasında oynamıştır?",
                "{name}'{~}n ilk oynadığı takımda hangi yıllar arasında oynamıştı?",
                "{name}'{~}n ilk oynadığı takımda hangi yıllar arasında oynadı?"
            ],
            "takım2": [
                "{name}'{~}n ikinci oynadığı takım hangisidir?",
                "{name}'{~}n oynadığı ikinci takım hangisidir?",
                "{name}'{~}n oynadığı ikinci takım nedir?",
                "{name}'{~}n oynadığı ikinci takımı ne",
                "{name}'{~}n ikinci takımı nedir?",
                "{name}'{~}n ikinci takımı hangisi?",
                "{name}'{~}n ikinci takımı hangisidir?",
                "{name}'{~}n kariyerindeki ikinci takım hangisidir?",
                "{name}'{~}n kariyerindeki ikinci takım nedir?",
                "{name}'{~}n profesyonel kariyerindeki ikinci takım hangisidir?",
                "{name}'{~}n profesyonel kariyerindeki ikinci takım hangisiydi?",
                "{name}'{~}n profesyonel kariyerindeki ikinci takım hangisi?",
                "{name}'{~}n profesyonel kariyerindeki ikinci takım neydi?",
                "{name}'{~}n profesyonel kariyerindeki ikinci takım nedir?"
            ],
            "takımyıl2": [
                "{name}'{~}n ikinci takımında ne zaman oynamıştır?",
                "{name}'{~}n ikinci takımında ne zamanlar oynamıştır?",
                "{name} ikinci takımında hangi yıllar oynamıştır?",
                "{name} ikinci takımında hangi yıllar oynadı?",
                "{name}'{~}n ikinci takımında oynadığı zaman aralığı nedir?",
                "{name} ikinci takımında oynadığı zaman aralığı nedir?",
                "{name}'{~}n ikinci oynadığı takımda ne zaman oynamıştır?",
                "{name} ikinci oynadığı takımda ne zaman oynamıştır?",
                "{name}'{~}n ikinci oynadığı takımda hangi yıllar arasında oynamıştır?",
                "{name}'{~}n ikinci oynadığı takımda hangi yıllar arasında oynamıştı?",
                "{name}'{~}n ikinci oynadığı takımda hangi yıllar arasında oynadı?",
                "{name}'{~}n oynadığı ikinci takımda hangi yıllar arasında oynadı?",
                "{name}'{~}n oynadığı ikinci takımda hangi yıllar arasında oynamıştır?",
                "{name}'{~}n oynadığı ikinci takımda hangi yıllar arasında oynamıştı?",
                "{name}'{~}n oynadığı ikinci takımda hangi periyotta oynamıştı?",
                "{name}'{~}n oynadığı ikinci takımda hangi periyotta oynamıştır?"
            ],
            "takım": [
                "{name} hangi takımda oynamaktadır?",
                "{name} şu an hangi takımda oynamaktadır?",
                "{name} hangi takımda oynuyor?",
                "{name} şu an hangi takımda oynuyor?",
                "{name} hangi takımın oyuncusudur?",
                "{name} şu an hangi takımın oyuncusudur?",
                "{name} hangi takımdadır?",
                "{name} şu an hangi takımdadır?",
                "{name}'{~}n oynadığı takım hangisidir?",
                "{name}'{~}n takımı hangisidir?",
                "{name}'{~}n güncel takımı hangisidir?",
                "{name}'{~}n şu an oynadığı takım hangisidir?"
            ],
            "lig": [
                "{name} hangi ligde oynamaktadır?",
                "{name} hangi ligde oynadı?",
                "{name} şu an hangi ligde oynamaktadır?",
                "{name} hangi ligde oynuyor?",
                "{name} şu an hangi ligde oynuyor?",
                "{name} hangi ligin oyuncusudur?",
                "{name} şu an hangi ligin oyuncusudur?",
                "{name} hangi ligdedir?",
                "{name} şu an hangi ligdedir?",
                "{name}'{~}n oynadığı lig hangisidir?",
                "{name}'{~}n ligi hangisidir?",
                "{name}'{~}n güncel ligi hangisidir?",
                "{name}'{~}n şu an oynadığı takım hangisidir?"
            ]
        },
        "Bilim adamı": {
            "doğumyeri": [
                "{name} nerede doğmuştur?",
                "{name} nerede doğdu",
                "{name} doğum yeri",
                "{name}'{~}n doğum yeri",
                "{name} doğum yeri neresi",
                "{name}'{~}n doğum yeri neresi",
                "{name}'{~}n doğum yeri neresidir",
                "{name} doğum yeri neresidir",
                "{name} nereli",
                "{name} memleketi",
                "{name}'{~}n memleketi",
                "{name} memleketi nedir",
                "{name}'{~}n memleketi nedir",
                "{name} doğduğu yer",
                "{name}'{~}n doğduğu yer",
                "{name} doğduğu yer neresidir",
                "{name}'{~}n doğduğu yer neresidir",
                "{name} doğduğu yer neresi",
                "{name}'{~}n doğduğu yer neresi",
                "{name} doğduğu il",
                "{name}'{~}n doğduğu il",
                "{name} hangi ilde doğdu",
                "{name} hangi ülkede doğdu",
                "{name} doğduğu ülke",
                "{name}'{~}n doğduğu ülke"
            ],
            "doğumtarihi": [
                "{name}'{~}n doğum tarihi",
                "{name}'{~}n doğum tarihi nedir",
                "{name}'{~}n doğum tarihi ne zaman",
                "{name}'{~}n doğum yılı",
                "{name}'{~}n doğum yılı nedir",
                "{name}'{~}n doğum yılı ne zaman",
                "{name}'{~}n doğum günü ne zaman",
                "{name}'{~}n doğum günü nedir",
                "{name} doğum tarihi",
                "{name} doğum tarihi nedir",
                "{name} doğum tarihi ne zaman",
                "{name} doğum yılı",
                "{name} doğum yılı nedir",
                "{name} doğum yılı ne zaman",
                "{name} doğum günü ne zaman",
                "{name} doğum günü nedir",
                "{name} ne zaman doğmuştur?",
                "{name} ne zaman doğdu",
                "{name} doğum zamanı"
            ],
            "ölümyeri": [
                "{name} nerede ölmüştür",
                "{name} nerede öldü",
                "{name} ölüm yeri",
                "{name}'{~}n ölüm yeri",
                "{name} ölüm yeri neresi",
                "{name}'{~}n ölüm yeri neresi",
                "{name}'{~}n ölüm yeri neresidir",
                "{name} ölüm yeri neresidir",
                "{name} öldüğü yer",
                "{name}'{~}n öldüğü yer",
                "{name} öldüğü yer neresidir",
                "{name}'{~}n öldüğü yer neresidir",
                "{name} öldüğü yer neresi",
                "{name}'{~}n ölüdüğü yer neresi",
                "{name} doğduğu il",
                "{name}'{~}n ölüdüğü il",
                "{name} hangi ilde öldü",
                "{name} hangi ülkede öldü",
                "{name} öldüğü ülke",
                "{name}'{~}n öldüğü ülke"
            ],
            "ölümtarihi": [
                "{name}'{~}n ölüm tarihi",
                "{name}'{~}n ölüm tarihi nedir",
                "{name}'{~}n ölüm tarihi ne zaman",
                "{name}'{~}n ölüm yılı",
                "{name}'{~}n ölüm yılı nedir",
                "{name}'{~}n ölüm yılı ne zaman",
                "{name}'{~}n ölüm günü ne zaman",
                "{name}'{~}n ölüm günü nedir",
                "{name} ölüm tarihi",
                "{name} ölüm tarihi nedir",
                "{name} ölüm tarihi ne zaman",
                "{name} ölüm yılı",
                "{name} ölüm yılı nedir",
                "{name} ölüm yılı ne zaman",
                "{name} ölüm günü ne zaman",
                "{name} ölüm günü nedir",
                "{name} ne zaman ölmüştür",
                "{name} ne zaman ölüm",
                "{name} ölüm zamanı",
                "{name}'{~}n ölüm zamanı"
            ],
            "milliyeti": [
                "{name} nerelidir?",
                "{name} hangi ülke asıllıdır?",
                "{name} hangi millettendir?",
                "{name}'{~}n hangi millettendir?"
            ],
            "çalıştığıyerler": [
                "{name}'{~}n çalıştığı yerler nedir?",
                "{name}'{~}n çalıştığı yerler nerelerdir?",
                "{name} nerelerde çalışmıştır?",
                "{name} nerelerde çalıştı?",
                "{name} nerelerde çalışmıştı?",
                "{name}'{~}n çalıştığı kurumlar",
                "{name}'{~}n çalıştığı kurumlar nerelerdir?",
                "{name} hangi kurumlarda çalışmıştır?",
                "{name}'{~}n çalıştığı kurumlar nedir?",
            ],
            "ödüller": [
                "{name} hangi ödüllere sahiptir?",
                "{name} hangi ödülleri almıştır?",
                "{name} aldığı ödüller",
                "{name} sahip olduğu ödüller nelerdir?",
                "{name}'{#} takdim edilen ödüller nelerdir?",
                "{name}'{#} verilen ödüller nelerdir?",
                "{name}'{~}n kazandığı ödüller nelerdir?",
                "{name}'{~}n sahip olduğu ödüller nelerdir?"
            ],
            "önemlibaşarıları": [
                "{name}'{~}n önemli başarıları nelerdir?",
                "{name}'{~}n sahip olduğu önemli başarılar nelerdir?",
                "{name}'{~}n elde ettiği önemli başarılar nelerdir?",
                "{name}'{~}n en önemli başarıları nelerdir?",
                "{name} en önemli başarıları nelerdir?"
            ],
            "vatandaşlığı": [
                "{name} hangi ülke vatandaşıdır?",
                "{name} hangi ülkenin vatandaşıdır?",
                "{name} nerenin vatandaşıdır?",
                "{name} vatandaşlığı hangi ülkedendir?",
                "{name}'{~}n vatandaşlığı hangi ülkedendir?",
                "{name}'{~}n vatandaşı olduğu ülke hangisidir?",
                "{name}'{~}n vatandaşı olduğu ülke nedir?",
                "{name}'{~}n vatandaşlığına sahip olduğu ülke nedir?",
                "{name}'{~}n vatandaşlığına sahip olduğu ülke hangisidir?"
            ]
        },
        "Buz patencisi": {
            "ülke": [
                "{name} hangi ülke vatandaşıdır?",
                "{name} hangi ülke adına mücadele etmektedir?",
                "{name} hangi ülkenin sporcusudur?",
                "{name} hangi ülkenin sporcusuydu?",
                "{name} hangi ülkenin sporcusu",
                "{name} hangi ülkenin vatandaşıdır?",
                "{name} nerenin vatandaşıdır?",
                "{name} vatandaşlığı hangi ülkedendir?",
                "{name}'{~}n vatandaşlığı hangi ülkedendir?",
                "{name}'{~}n vatandaşı olduğu ülke hangisidir?",
                "{name}'{~}n vatandaşı olduğu ülke nedir?",
                "{name}'{~}n vatandaşlığına sahip olduğu ülke nedir?",
                "{name}'{~}n vatandaşlığına sahip olduğu ülke hangisidir?"
            ],
            "koç": [
                "{name}'{~}n koçu kimdir?",
                "{name}'{~}n koçu kim?",
                "{name}'{~}n koçu kimdi?",
                "{name}'{~}n spor koçu kimdi?"
            ]
        },
        "Filozof": {
            "çağ": [
                "{name} hangi çağda yaşamaktaydı?",
                "{name} hangi çağda yaşadı?"
            ],
            "bölge": [
                "{name} hangi bölgede yaşamaktaydı?",
                "{name} hangi bölgede yaşadı?"
            ],
            "etkilendikleri": [
                "{name} kimlerden etkilenmiştir?",
                "{name} kimlerden etkilendi?",
                "{name}'{~}n etkilendiği kişiler kimlerdir?"
            ],
            "etkiledikleri": [
                "{name} kimleri etkilemiştir?",
                "{name} kimleri etkiledi?",
                "{name}'{~}n etkilediği kişiler kimlerdir?"
            ],
            "ilgialanları": [
                "{name}'{~}n ilgi alanları nelerdir?",
                "{name}'{~}n ilgi alanları nelerdi?",
                "{name}'{~}n ilgi alanları neydi?"
            ],
            "okulgelenek":[
                "{name}'{~}n okulunun geleneği nedir?",
                "{name}'{~}n okulunun gelenekleri nelerdir?"
            ]
        },
        "Hakem": {},
        "Güreşçi": {
            "doğumyeri": [
                "{name} nerede doğmuştur?",
                "{name} nerede doğdu",
                "{name} doğum yeri",
                "{name}'{~}n doğum yeri",
                "{name} doğum yeri neresi",
                "{name}'{~}n doğum yeri neresi",
                "{name}'{~}n doğum yeri neresidir",
                "{name} doğum yeri neresidir",
                "{name} nereli",
                "{name} memleketi",
                "{name}'{~}n memleketi",
                "{name} memleketi nedir",
                "{name}'{~}n memleketi nedir",
                "{name} doğduğu yer",
                "{name}'{~}n doğduğu yer",
                "{name} doğduğu yer neresidir",
                "{name}'{~}n doğduğu yer neresidir",
                "{name} doğduğu yer neresi",
                "{name}'{~}n doğduğu yer neresi",
                "{name} doğduğu il",
                "{name}'{~}n doğduğu il",
                "{name} hangi ilde doğdu",
                "{name} hangi ülkede doğdu",
                "{name} doğduğu ülke",
                "{name}'{~}n doğduğu ülke"
            ],
            "debut": [
                "{name}'{~}n ilk ringe çıkışı ne zamandır?",
                "{name}'{~}n ilk maça çıkışı ne zamandır?",
                "{name} ilk maçına ne zaman çıkmıştır?",
                "{name} ilk olarak ringe ne zaman çıkmıştır?"
            ],
            "doğumtarihi": [
                "{name}'{~}n doğum tarihi",
                "{name}'{~}n doğum tarihi nedir",
                "{name}'{~}n doğum tarihi ne zaman",
                "{name}'{~}n doğum yılı",
                "{name}'{~}n doğum yılı nedir",
                "{name}'{~}n doğum yılı ne zaman",
                "{name}'{~}n doğum günü ne zaman",
                "{name}'{~}n doğum günü nedir",
                "{name} doğum tarihi",
                "{name} doğum tarihi nedir",
                "{name} doğum tarihi ne zaman",
                "{name} doğum yılı",
                "{name} doğum yılı nedir",
                "{name} doğum yılı ne zaman",
                "{name} doğum günü ne zaman",
                "{name} doğum günü nedir",
                "{name} ne zaman doğmuştur?",
                "{name} ne zaman doğdu",
                "{name} doğum zamanı"
            ],
            "ringadları": [
                "{name}'{~}n ring adları nelerdir?",
                "{name}'{~}n ring adları nedir?",
                "{name}'{~}n ring adı nedir?"
            ],
            "eğiten": [
                "{name}'{~} eğiten kişiler kimlerdir?",
                "{name}'{~} eğiten kişiler kimler?",
                "{name}'{~} eğiten kişilerin adları nelerdir?",
                "{name}'{~} eğiten kişilerin adları ne?"
            ],
            "eğitildiğiyer": [
                "{name} nerede eğitilmiştir?",
                "{name} nerede eğitildi?",
                "{name} eğitildiği yer neresidir?",
                "{name} eğitildiği yer neresi"
            ],
            "yaşadığıyer":[
                "{name} nerede yaşamaktadır?",
                "{name} yaşadığı yer neresidir?",
                "{name} yaşadığı yer neresi"
            ],
            "emekliliği": [
                "{name} hangi yılda emekli olmuştur?",
                "{name} hangi yılda emekli olmuştu?"
            ]
        },
        "Futbolcu": {
            "doğumyeri": [
                "{name} nerede doğmuştur?",
                "{name} nerede doğdu",
                "{name} doğum yeri",
                "{name}'{~}n doğum yeri",
                "{name} doğum yeri neresi",
                "{name}'{~}n doğum yeri neresi",
                "{name}'{~}n doğum yeri neresidir",
                "{name} doğum yeri neresidir",
                "{name} nereli",
                "{name} memleketi",
                "{name}'{~}n memleketi",
                "{name} memleketi nedir",
                "{name}'{~}n memleketi nedir",
                "{name} doğduğu yer",
                "{name}'{~}n doğduğu yer",
                "{name} doğduğu yer neresidir",
                "{name}'{~}n doğduğu yer neresidir",
                "{name} doğduğu yer neresi",
                "{name}'{~}n doğduğu yer neresi",
                "{name} doğduğu il",
                "{name}'{~}n doğduğu il",
                "{name} hangi ilde doğdu",
                "{name} hangi ülkede doğdu",
                "{name} doğduğu ülke",
                "{name}'{~}n doğduğu ülke"
            ],
            "pozisyon": [
                "{name} hangi pozisyonda oynamaktadır?",
                "{name} hangi pozisyonda oynar?",
                "{name} hangi pozisyonda oynuyor?",
                "{name} hangi mevkiide oynamaktadır?",
                "{name} hangi mevkiide oynar?",
                "{name} hangi mevkiide oynuyor?",
                "{name}'{~}n oynadığı pozisyon nedir?",
                "{name}'{~}n oynamakta olduğu pozisyon nedir?",
                "{name}'{~}n pozisyonu nedir?",
                "{name}'{~}n oyun pozisyonu nedir?",
                "{name}'{~}n maçlardaki pozisyonu nedir?"
            ],
            "doğumtarihi": [
                "{name}'{~}n doğum tarihi",
                "{name}'{~}n doğum tarihi nedir",
                "{name}'{~}n doğum tarihi ne zaman",
                "{name}'{~}n doğum yılı",
                "{name}'{~}n doğum yılı nedir",
                "{name}'{~}n doğum yılı ne zaman",
                "{name}'{~}n doğum günü ne zaman",
                "{name}'{~}n doğum günü nedir",
                "{name} doğum tarihi",
                "{name} doğum tarihi nedir",
                "{name} doğum tarihi ne zaman",
                "{name} doğum yılı",
                "{name} doğum yılı nedir",
                "{name} doğum yılı ne zaman",
                "{name} doğum günü ne zaman",
                "{name} doğum günü nedir",
                "{name} ne zaman doğmuştur?",
                "{name} ne zaman doğdu",
                "{name} doğum zamanı"
            ],
            "tamadı": [
                "{name}'{~}n tam adı nedir?",
                "{name}'{~}n tam adı neydi",
                "{name}'{~}n tam adı ne",
                "{name}'{~}n tam adı ne idi"
            ],
            "kulüp1": [
                "{name}'{~}n ilk oynadığı takım hangisidir?",
                "{name}'{~}n oynadığı ilk takım hangisidir?",
                "{name}'{~}n ilk takımı hangisi?",
                "{name}'{~}n ilk takımı hangisidir?",
                "{name}'{~}n kariyerine başladığı takım hangisidir?",
                "{name}'{~}n kariyerindeki ilk takım hangisidir?",
                "{name} profesyonel kariyerine hangi takımda başlamıştır?",
                "{name} profesyonel kariyerine hangi takımla başlamıştır?",
                "{name} profesyonel kariyerine hangi takımla adım atmıştır?",
                "{name}'{~}n profesyonel kariyerindeki ilk takım hangisidir?",
                "{name}'{~}n profesyonel kariyerindeki ilk takım hangisiydi?",
                "{name}'{~}n profesyonel kariyerindeki ilk takım hangisi?",
                "{name}'{~}n profesyonel kariyerindeki ilk takım neydi?",
                "{name}'{~}n profesyonel kariyerindeki ilk takım nedir?",
                "{name}'{~}n ilk oynadığı kulüp hangisidir?",
                "{name}'{~}n oynadığı ilk kulüp hangisidir?",
                "{name}'{~}n ilk kulübü hangisi?",
                "{name}'{~}n ilk kulübü hangisidir?",
                "{name}'{~}n kariyerine başladığı kulüp hangisidir?",
                "{name}'{~}n kariyerindeki ilk kulüp hangisidir?",
                "{name} profesyonel kariyerine hangi kulüpte başlamıştır?",
                "{name} profesyonel kariyerine hangi kulüple başlamıştır?",
                "{name} profesyonel kariyerine hangi kulüple adım atmıştır?",
                "{name}'{~}n profesyonel kariyerindeki ilk kulüp hangisidir?",
                "{name}'{~}n profesyonel kariyerindeki ilk kulüp hangisiydi?",
                "{name}'{~}n profesyonel kariyerindeki ilk kulüp hangisi?",
                "{name}'{~}n profesyonel kariyerindeki ilk kulüp neydi?",
                "{name}'{~}n profesyonel kariyerindeki ilk kulüp nedir?"
            ],
            "kulüpyıl1": [
                "{name} profesyonel kariyerine ne zaman başlamıştır?",
                "{name}'{~}n profesyonel kariyerine başlangıcı ne zamandır?",
                "{name}'{~}n profesyonel kariyerine başlangıcı ne zamandı",
                "{name}'{~}n profesyonel kariyerine başlangıcı ne zaman",
                "{name}'{~}n profesyonel kariyerine başlangıcı ne zaman oldu?",
                "{name}'{~}n profesyonel kariyerine başlangıcı ne zaman olmuştur?",
                "{name} profesyonel kariyerine hangi yılda başladı?",
                "{name} profesyonel kariyerine hangi yılda başlamıştı?",
                "{name} profesyonel kariyerine hangi yılda başlamıştır?",
                "{name} profesyonel kariyerine ne zaman başladı?",
                "{name} profesyonel kariyerine ne zaman başlamıştı?",
                "{name} profesyonel kariyerine ne zaman başlamıştır?",
                "{name}'{~}n ilk takımında ne zaman oynamıştır?",
                "{name}'{~}n ilk takımında ne zamanlar oynamıştır?",
                "{name}'{~}n ilk takımında hangi yıllar oynamıştır?",
                "{name}'{~}n ilk takımında hangi yıllar oynadı?",
                "{name}'{~}n ilk takımında oynadığı zaman aralığı nedir?",
                "{name}'{~}n ilk takımında oynadığı zaman aralığı nedir?",
                "{name}'{~}n ilk oynadığı takımda ne zaman oynamıştır?",
                "{name}'{~}n ilk oynadığı takımda hangi yıllar arasında oynamıştır?",
                "{name}'{~}n ilk oynadığı takımda hangi yıllar arasında oynamıştı?",
                "{name}'{~}n ilk oynadığı takımda hangi yıllar arasında oynadı?"
            ],
            "kulüp2": [
                "{name}'{~}n ikinci oynadığı takım hangisidir?",
                "{name}'{~}n oynadığı ikinci takım hangisidir?",
                "{name}'{~}n oynadığı ikinci takım nedir?",
                "{name}'{~}n oynadığı ikinci takımı ne",
                "{name}'{~}n ikinci takımı nedir?",
                "{name}'{~}n ikinci takımı hangisi?",
                "{name}'{~}n ikinci takımı hangisidir?",
                "{name}'{~}n kariyerindeki ikinci takım hangisidir?",
                "{name}'{~}n kariyerindeki ikinci takım nedir?",
                "{name}'{~}n profesyonel kariyerindeki ikinci takım hangisidir?",
                "{name}'{~}n profesyonel kariyerindeki ikinci takım hangisiydi?",
                "{name}'{~}n profesyonel kariyerindeki ikinci takım hangisi?",
                "{name}'{~}n profesyonel kariyerindeki ikinci takım neydi?",
                "{name}'{~}n profesyonel kariyerindeki ikinci takım nedir?"
            ],
            "kulüpyıl2": [
                "{name}'{~}n ikinci takımında ne zaman oynamıştır?",
                "{name}'{~}n ikinci takımında ne zamanlar oynamıştır?",
                "{name} ikinci takımında hangi yıllar oynamıştır?",
                "{name} ikinci takımında hangi yıllar oynadı?",
                "{name}'{~}n ikinci takımında oynadığı zaman aralığı nedir?",
                "{name} ikinci takımında oynadığı zaman aralığı nedir?",
                "{name}'{~}n ikinci oynadığı takımda ne zaman oynamıştır?",
                "{name} ikinci oynadığı takımda ne zaman oynamıştır?",
                "{name}'{~}n ikinci oynadığı takımda hangi yıllar arasında oynamıştır?",
                "{name}'{~}n ikinci oynadığı takımda hangi yıllar arasında oynamıştı?",
                "{name}'{~}n ikinci oynadığı takımda hangi yıllar arasında oynadı?",
                "{name}'{~}n oynadığı ikinci takımda hangi yıllar arasında oynadı?",
                "{name}'{~}n oynadığı ikinci takımda hangi yıllar arasında oynamıştır?",
                "{name}'{~}n oynadığı ikinci takımda hangi yıllar arasında oynamıştı?",
                "{name}'{~}n oynadığı ikinci takımda hangi periyotta oynamıştı?",
                "{name}'{~}n oynadığı ikinci takımda hangi periyotta oynamıştır?"
            ]
        },
        "Kişi": {
            "meslek":[
                "{name}'{~}n mesleği nedir?",
                "{name}'{~}n mesleği neydi",
                "{name} ne iş yapar?",
                "{name} işi ne?",
                "{name} işi nedir?"
            ],
            "aktifyılları":[
                "{name} hangi yıllar arası aktifti?",
                "{name} hangi yıllar arası aktif kalmıştır?",
                "{name}'{~}n aktif yılları nedir?"
            ],
            "yer":[
                "{name} nerede yaşamaktadır?",
                "{name} yaşadığı yer neresidir?",
                "{name} yaşadığı yer neresi"
            ],
            "etinyılları":[
                "{name} hangi yıllar arası etkindi?",
                "{name} hangi yıllar arası etkin kalmıştır?",
                "{name}'{~}n etkin yılları nedir?"
            ],
        },
        "Kraliyet": {
            "hükümsüresi":[
                "{name} hangi yıllar arası hüküm sürmüştür?",
                "{name} hangi yıllar arası hüküm sürdü?",
                "{name} hangi yıllar arasında hüküm sürdü?",
                "{name} hangi yıllar arasında hüküm sürmüştür?"
            ],
            "sonragelen":[
                "{name}'{den} sonra gelen hükümdar kim?",
            ],
            "ölümtarihi":[],
            "öncegelen":[
                "{name}'{den} önce gelen hükümdar kimdir?",
                "{name}'{den} önce gelen hükümdar kim?",
            ],
            "babası":[
                "{name}'{~}n babası kimdir?",
                "{name}'{~}n babası kim?"
            ],
            "hanedan":[
                "{name}'{~}n hanedanı nedir?",
                "{name}'{~}n hanedanı ne?",
                "{name} hangi hanedandandır?",
                "{name} hangi hanedandan?",
            ],
            "annesi":[
                "{name}'{~}n annesi kimdir?",
                "{name}'{~}n annesi kim?"
            ],
            "ölümyeri": [
                "{name} nerede ölmüştür",
                "{name} nerede öldü",
                "{name} ölüm yeri",
                "{name}'{~}n ölüm yeri",
                "{name} ölüm yeri neresi",
                "{name}'{~}n ölüm yeri neresi",
                "{name}'{~}n ölüm yeri neresidir",
                "{name} ölüm yeri neresidir",
                "{name} öldüğü yer",
                "{name}'{~}n öldüğü yer",
                "{name} öldüğü yer neresidir",
                "{name}'{~}n öldüğü yer neresidir",
                "{name} öldüğü yer neresi",
                "{name}'{~}n ölüdüğü yer neresi",
                "{name} doğduğu il",
                "{name}'{~}n ölüdüğü il",
                "{name} hangi ilde öldü",
                "{name} hangi ülkede öldü",
                "{name} öldüğü ülke",
                "{name}'{~}n öldüğü ülke"
            ],
        },
        "Makam sahibi": {
            "makam":[
                "{name} hangi makama sahiptir?",
                "{name} hangi makamdadır?",
                "{name} hangi makamda görev almıştır?",
                "{name}'{~}n görevi nedir"
            ],
            "dönembaşı":[
                "{name} hangi yılda göreve başlamıştır?",
                "{name} hangi yılda göreve başlamıştı?",
                "{name} hangi yılda göreve başladı?",
                "{name} dönemi ne zaman başlamıştır?"
            ],
            "öncegelen":[
                "{name}'{den}n önce gelen kişi kimdir?",
                "{name}'{den}n önce gelen kişi kim?",
                "{name}'{den}n önce görev alan kişi kim?",
                "{name}'{den}n önce görev alan kişi kimdir?"
            ],
            "dönemsonu":[
                "{name} hangi yılda görevi sona ermiştir?",
                "{name} hangi yılda görevi bitmiştir?",
                "{name} hangi yılda görevi bitti?",
                "{name} dönemi ne zaman bitmiştir?"
            ],
            "sonragelen":[
                "{name}'{den}n sonra gelen kişi kimdir?",
                "{name}'{den}n sonra gelen kişi kim?",
                "{name}'{den}n sonra görev alan kişi kim?",
                "{name}'{den}n sonra görev alan kişi kimdir?"
            ],
            "partisi":[
                "{name} hanginin bir mensubudur?",
                "{name}'{~}n partisi nedir?",
                "{name}'{~}n partisi ne?"
            ]
        },
        "Manken": {
            "gözrengi":[
                "{name}'{~}n göz rengi nedir?",
                "{name}'{~}n göz rengi ne?"
            ],
            "saçrengi":[
                "{name}'{~}n saç rengi nedir?",
                "{name}'{~}n saç rengi ne?"
            ],
            "ulus": [
                "{name} nerelidir?",
                "{name} hangi ülke asıllıdır?",
                "{name} hangi millettendir?",
                "{name}'{~}n hangi millettendir?"
            ],
            "boy": [
                "{name}'{~}n boyu ne kadardır?",
                "{name}'{~}n boyu nedir?",
                "{name}'{~}n boyu ne"
            ]
        },
        "Müzik sanatçısı": {
            "artalan": [
                "{name}'{~}n art alanı nedir?",
                "{name}'{~}n art alanı ne"
            ],
            "tarz": [
                "{name} hangi tür müzik yapar?",
                "{name} hangi tür müzik yaptı?",
                "{name} hangi tür müzik yapmaktadır?",
                "{name}'{~}n hangi tarzda müzik yapmaktadır?",
                "{name}'{~}n hangi tarzda müzik yapmakta",
                "{name}'{~}n hangi tarzda müzik yapar?",
                "{name}'{~}n hangi tarzlarda müzik yapmaktadır?",
                "{name}'{~}n hangi tarzlarda müzik yapmakta",
                "{name}'{~}n hangi tarzlarda müzik yapar?",
                "{name}'{~}n ne tarzda müzik yapmaktadır?",
                "{name}'{~}n ne tarzda müzik yapmaktadır?",
                "{name}'{~}n ne tarzda müzik yapar?",
                "{name}'{~}n ne tarzlarda müzik yapmaktadır?",
                "{name}'{~}n ne tarzlarda müzik yapmaktadır?",
                "{name}'{~}n ne tarzlarda müzik yapar?"
            ],
            "etkinyıllar": [
                "{name} hangi yıllarda aktif olarak müzik yapmıştır?",
                "{name} hangi yıllarda aktif olarak müzik yapmıştı?",
                "{name} aktif yılları nelerdir?"
                "{name} aktif yılları nedir?"
                "{name} etkin yılları nelerdir?"
                "{name} etkin yılları nedir?"
                "{name} etkin olduğu yıllar nedir?"
            ],
            "meslek": [
                "{name}'{~}n mesleği",
                "{name}'{~}n mesleği ne",
                "{name}'{~}n mesleği neydi",
                "{name}'{~}n gerçek mesleği",
                "{name}'{~}n gerçek mesleği nedir?",
                "{name}'{~}n gerçek mesleği neydi",
                "{name}'{~}n mesleği nedir?",
                "{name} mesleği nedir?",
                "{name} mesleği ne idi?",
                "{name} hangi mesleğe mensuptur?",
                "{name} hangi mesleğe mensup?",
                "{name} hangi mesleği yapıyordu?",
                "{name} hangi işi yapıyor?",
                "{name} hangi işi yapıyordu?"
            ],
            "plakşirketi": [
                "{name} hangi plak şirketiyle çalışmaktadır?",
                "{name} hangi plak şirketiyle çalışıyordu?",
                "{name} hangi plak şirketiyle çalışıyor?",
            ],
            "köken": [
                "{name} nerelidir?",
                "{name} hangi ülke asıllıdır?",
                "{name} hangi millettendir?",
                "{name}'{~}n hangi millettendir?",
                "{name} kökeni nedir?",
                "{name} kökeni ne",
                "{name} kökeni neydi"
            ],
            "çalgı": [
                "{name} hangi çalgıyı çalmaktadır?",
                "{name} hangi çalgıyı çalar?",
                "{name} hangi çalgıyı çalıyor?",
                "{name} hangi müzik aletini çalmaktadır?",
                "{name} hangi müzik aletini çalar?",
                "{name} hangi müzik aletini çalıyor?"
            ]
        },
        "Oyuncu": {
            "yer": [
                "{name} nerede yaşamaktadır?",
                "{name} yaşadığı yer neresidir?",
                "{name} yaşadığı yer neresi"
            ],
            "doğumtarihi": [
                "{name}'{~}n doğum tarihi",
                "{name}'{~}n doğum tarihi nedir",
                "{name}'{~}n doğum tarihi ne zaman",
                "{name}'{~}n doğum yılı",
                "{name}'{~}n doğum yılı nedir",
                "{name}'{~}n doğum yılı ne zaman",
                "{name}'{~}n doğum günü ne zaman",
                "{name}'{~}n doğum günü nedir",
                "{name} doğum tarihi",
                "{name} doğum tarihi nedir",
                "{name} doğum tarihi ne zaman",
                "{name} doğum yılı",
                "{name} doğum yılı nedir",
                "{name} doğum yılı ne zaman",
                "{name} doğum günü ne zaman",
                "{name} doğum günü nedir",
                "{name} ne zaman doğmuştur?",
                "{name} ne zaman doğdu",
                "{name} doğum zamanı"
            ],
            "meslek": [
                "{name}'{~}n mesleği",
                "{name}'{~}n mesleği ne",
                "{name}'{~}n mesleği neydi",
                "{name}'{~}n gerçek mesleği",
                "{name}'{~}n gerçek mesleği nedir?",
                "{name}'{~}n gerçek mesleği neydi",
                "{name}'{~}n mesleği nedir?",
                "{name} mesleği nedir?",
                "{name} mesleği ne idi?",
                "{name} hangi mesleğe mensuptur?",
                "{name} hangi mesleğe mensup?",
                "{name} hangi mesleği yapıyordu?",
                "{name} hangi işi yapıyor?",
                "{name} hangi işi yapıyordu?"
            ],
            "etkinyıllar": [
                "{name} hangi yıllarda aktif olarak rol almıştır?",
                "{name} hangi yıllarda aktif olarak rol almıştı?",
                "{name} hangi yıllarda aktif olarak rol almıştı?",
                "{name} aktif yılları nelerdir?"
                "{name} aktif yılları nedir?"
                "{name} etkin yılları nelerdir?"
                "{name} etkin yılları nedir?"
                "{name} etkin olduğu yıllar nedir?"
            ],
            "evlilik": [
                "{name} eşi kimdir?"
                "{name}'{~}n eşi kimdir?",
                "{name} kiminle evlidir?",
                "{name} kiminle evlendi?"
            ],
            "ulus": [
                "{name} nerelidir?",
                "{name} hangi ülke asıllıdır?",
                "{name} hangi millettendir?",
                "{name}'{~}n hangi millettendir?"
            ],
            "ölümtarihi": [
                "{name}'{~}n ölüm tarihi",
                "{name}'{~}n ölüm tarihi nedir",
                "{name}'{~}n ölüm tarihi ne zaman",
                "{name}'{~}n ölüm yılı",
                "{name}'{~}n ölüm yılı nedir",
                "{name}'{~}n ölüm yılı ne zaman",
                "{name}'{~}n ölüm günü ne zaman",
                "{name}'{~}n ölüm günü nedir",
                "{name} ölüm tarihi",
                "{name} ölüm tarihi nedir",
                "{name} ölüm tarihi ne zaman",
                "{name} ölüm yılı",
                "{name} ölüm yılı nedir",
                "{name} ölüm yılı ne zaman",
                "{name} ölüm günü ne zaman",
                "{name} ölüm günü nedir",
                "{name} ne zaman ölmüştür",
                "{name} ne zaman ölüm",
                "{name} ölüm zamanı",
                "{name}'{~}n ölüm zamanı"
            ],
            "ölümyeri": [
                "{name} nerede ölmüştür",
                "{name} nerede öldü",
                "{name} ölüm yeri",
                "{name}'{~}n ölüm yeri",
                "{name} ölüm yeri neresi",
                "{name}'{~}n ölüm yeri neresi",
                "{name}'{~}n ölüm yeri neresidir",
                "{name} ölüm yeri neresidir",
                "{name} öldüğü yer",
                "{name}'{~}n öldüğü yer",
                "{name} öldüğü yer neresidir",
                "{name}'{~}n öldüğü yer neresidir",
                "{name} öldüğü yer neresi",
                "{name}'{~}n ölüdüğü yer neresi",
                "{name} doğduğu il",
                "{name}'{~}n ölüdüğü il",
                "{name} hangi ilde öldü",
                "{name} hangi ülkede öldü",
                "{name} öldüğü ülke",
                "{name}'{~}n öldüğü ülke"
            ]
        },
        "Profesyonel güreşçi": {
            "doğumyeri": [
                "{name} nerede doğmuştur?",
                "{name} nerede doğdu",
                "{name} doğum yeri",
                "{name}'{~}n doğum yeri",
                "{name} doğum yeri neresi",
                "{name}'{~}n doğum yeri neresi",
                "{name}'{~}n doğum yeri neresidir",
                "{name} doğum yeri neresidir",
                "{name} nereli",
                "{name} memleketi",
                "{name}'{~}n memleketi",
                "{name} memleketi nedir",
                "{name}'{~}n memleketi nedir",
                "{name} doğduğu yer",
                "{name}'{~}n doğduğu yer",
                "{name} doğduğu yer neresidir",
                "{name}'{~}n doğduğu yer neresidir",
                "{name} doğduğu yer neresi",
                "{name}'{~}n doğduğu yer neresi",
                "{name} doğduğu il",
                "{name}'{~}n doğduğu il",
                "{name} hangi ilde doğdu",
                "{name} hangi ülkede doğdu",
                "{name} doğduğu ülke",
                "{name}'{~}n doğduğu ülke"
            ],
            "debut": [
                "{name}'{~}n ilk ringe çıkışı ne zamandır?",
                "{name}'{~}n ilk maça çıkışı ne zamandır?",
                "{name} ilk maçına ne zaman çıkmıştır?",
                "{name} ilk olarak ringe ne zaman çıkmıştır?"
            ],
            "doğumtarihi": [
                "{name}'{~}n doğum tarihi",
                "{name}'{~}n doğum tarihi nedir",
                "{name}'{~}n doğum tarihi ne zaman",
                "{name}'{~}n doğum yılı",
                "{name}'{~}n doğum yılı nedir",
                "{name}'{~}n doğum yılı ne zaman",
                "{name}'{~}n doğum günü ne zaman",
                "{name}'{~}n doğum günü nedir",
                "{name} doğum tarihi",
                "{name} doğum tarihi nedir",
                "{name} doğum tarihi ne zaman",
                "{name} doğum yılı",
                "{name} doğum yılı nedir",
                "{name} doğum yılı ne zaman",
                "{name} doğum günü ne zaman",
                "{name} doğum günü nedir",
                "{name} ne zaman doğmuştur?",
                "{name} ne zaman doğdu",
                "{name} doğum zamanı"
            ],
            "ringadları": [
                "{name}'{~}n ring adları nelerdir?",
                "{name}'{~}n ring adları nedir?",
                "{name}'{~}n ring adı nedir?"
            ],
            "eğiten": [
                "{name}'{~} eğiten kişiler kimlerdir?",
                "{name}'{~} eğiten kişiler kimler?",
                "{name}'{~} eğiten kişilerin adları nelerdir?",
                "{name}'{~} eğiten kişilerin adları ne?"
            ],
            "eş": [
                "{name} kimle evlidir?",
                "{name}'{~}n evli olduğu kişi kimdir?",
            ],
            "eğitildiğiyer": [
                "{name} nerede eğitilmiştir?",
                "{name} nerede eğitildi?",
                "{name} eğitildiği yer neresidir?",
                "{name} eğitildiği yer neresi"
            ],
            "çocuklar": [
                "{name}'{~}n çocukları kimlerdir?",
                "{name}'{~}n çocukları kim?",
                "{name}'{~}n çocuklarının adları nedir?",
                "{name}'{~}n çocuklarının adları nelerdir?",
                "{name} çocukları kimdir?",
                "{name} çocuklarının isimleri nedir?",
                "{name} çocuklarının isimleri?"
            ]
        },
        "Sanatçı": {
            "doğumtarihi": [
                "{name}'{~}n doğum tarihi",
                "{name}'{~}n doğum tarihi nedir",
                "{name}'{~}n doğum tarihi ne zaman",
                "{name}'{~}n doğum yılı",
                "{name}'{~}n doğum yılı nedir",
                "{name}'{~}n doğum yılı ne zaman",
                "{name}'{~}n doğum günü ne zaman",
                "{name}'{~}n doğum günü nedir",
                "{name} doğum tarihi",
                "{name} doğum tarihi nedir",
                "{name} doğum tarihi ne zaman",
                "{name} doğum yılı",
                "{name} doğum yılı nedir",
                "{name} doğum yılı ne zaman",
                "{name} doğum günü ne zaman",
                "{name} doğum günü nedir",
                "{name} ne zaman doğmuştur?",
                "{name} ne zaman doğdu",
                "{name} doğum zamanı"
            ],
            "alanı": [
                "{name}'{~}n alanı nedir?",
                "{name}'{~}n alanı ne",
                "{name} hangi alanda sanat yapmaktadır?",
                "{name} hangi alanda sanat yapmaktaydı?",
                "{name} hangi alanda sanat yapıyor?",
                "{name} hangi alanda eser vermektedir"
            ],
            "ölümtarihi": [
                "{name}'{~}n ölüm tarihi",
                "{name}'{~}n ölüm tarihi nedir",
                "{name}'{~}n ölüm tarihi ne zaman",
                "{name}'{~}n ölüm yılı",
                "{name}'{~}n ölüm yılı nedir",
                "{name}'{~}n ölüm yılı ne zaman",
                "{name}'{~}n ölüm günü ne zaman",
                "{name}'{~}n ölüm günü nedir",
                "{name} ölüm tarihi",
                "{name} ölüm tarihi nedir",
                "{name} ölüm tarihi ne zaman",
                "{name} ölüm yılı",
                "{name} ölüm yılı nedir",
                "{name} ölüm yılı ne zaman",
                "{name} ölüm günü ne zaman",
                "{name} ölüm günü nedir",
                "{name} ne zaman ölmüştür",
                "{name} ne zaman ölüm",
                "{name} ölüm zamanı",
                "{name}'{~}n ölüm zamanı"
            ],
            "ölümyeri": [
                "{name} nerede ölmüştür",
                "{name} nerede öldü",
                "{name} ölüm yeri",
                "{name}'{~}n ölüm yeri",
                "{name} ölüm yeri neresi",
                "{name}'{~}n ölüm yeri neresi",
                "{name}'{~}n ölüm yeri neresidir",
                "{name} ölüm yeri neresidir",
                "{name} öldüğü yer",
                "{name}'{~}n öldüğü yer",
                "{name} öldüğü yer neresidir",
                "{name}'{~}n öldüğü yer neresidir",
                "{name} öldüğü yer neresi",
                "{name}'{~}n ölüdüğü yer neresi",
                "{name} doğduğu il",
                "{name}'{~}n ölüdüğü il",
                "{name} hangi ilde öldü",
                "{name} hangi ülkede öldü",
                "{name} öldüğü ülke",
                "{name}'{~}n öldüğü ülke"
            ],
            "doğumyeri": [
                "{name} nerede doğmuştur?",
                "{name} nerede doğdu",
                "{name} doğum yeri",
                "{name}'{~}n doğum yeri",
                "{name} doğum yeri neresi",
                "{name}'{~}n doğum yeri neresi",
                "{name}'{~}n doğum yeri neresidir",
                "{name} doğum yeri neresidir",
                "{name} nereli",
                "{name} memleketi",
                "{name}'{~}n memleketi",
                "{name} memleketi nedir",
                "{name}'{~}n memleketi nedir",
                "{name} doğduğu yer",
                "{name}'{~}n doğduğu yer",
                "{name} doğduğu yer neresidir",
                "{name}'{~}n doğduğu yer neresidir",
                "{name} doğduğu yer neresi",
                "{name}'{~}n doğduğu yer neresi",
                "{name} doğduğu il",
                "{name}'{~}n doğduğu il",
                "{name} hangi ilde doğdu",
                "{name} hangi ülkede doğdu",
                "{name} doğduğu ülke",
                "{name}'{~}n doğduğu ülke"
            ],
            "milliyeti": [
                "{name} nerelidir?",
                "{name} hangi ülke asıllıdır?",
                "{name} hangi millettendir?",
                "{name}'{~}n hangi millettendir?"
            ],
            "yer": [
                "{name} nerede yaşamaktadır?",
                "{name} yaşadığı yer neresidir?",
                "{name} yaşadığı yer neresi"
            ],
            "ünlüyapıtları": [
                "{name}'{~}n ünlü yapıtları nelerdir?",
                "{name}'{~}n ünlü yapıtları nedir?",
                "{name}'{~}n yarattığı ünlü yapıtlar nelerdir?",
                "{name}'{~}n yarattığı ünlü yapıtlar nedir?",
            ]
        },
        "Sporcu": {
            "doğumtarihi": [
                "{name}'{~}n doğum tarihi",
                "{name}'{~}n doğum tarihi nedir?",
                "{name}'{~}n doğum tarihi ne zaman",
                "{name}'{~}n doğum yılı",
                "{name}'{~}n doğum yılı nedir",
                "{name}'{~}n doğum yılı ne zaman",
                "{name}'{~}n doğum günü ne zaman",
                "{name}'{~}n doğum günü nedir",
                "{name} doğum tarihi",
                "{name} doğum tarihi nedir",
                "{name} doğum tarihi ne zaman",
                "{name} doğum yılı",
                "{name} doğum yılı nedir",
                "{name} doğum yılı ne zaman",
                "{name} doğum günü ne zaman",
                "{name} doğum günü nedir",
                "{name} ne zaman doğmuştur?",
                "{name} ne zaman doğdu",
                "{name} doğum zamanı"
            ],
            "doğumyeri": [
                "{name} nerede doğmuştur?",
                "{name} nerede doğdu",
                "{name} doğum yeri",
                "{name}'{~}n doğum yeri",
                "{name} doğum yeri neresi",
                "{name}'{~}n doğum yeri neresi",
                "{name}'{~}n doğum yeri neresidir",
                "{name} doğum yeri neresidir",
                "{name} nereli",
                "{name} memleketi",
                "{name}'{~}n memleketi",
                "{name} memleketi nedir",
                "{name}'{~}n memleketi nedir",
                "{name} doğduğu yer",
                "{name}'{~}n doğduğu yer",
                "{name} doğduğu yer neresidir",
                "{name}'{~}n doğduğu yer neresidir",
                "{name} doğduğu yer neresi",
                "{name}'{~}n doğduğu yer neresi",
                "{name} doğduğu il",
                "{name}'{~}n doğduğu il",
                "{name} hangi ilde doğdu",
                "{name} hangi ülkede doğdu",
                "{name} doğduğu ülke",
                "{name}'{~}n doğduğu ülke"
            ],
            "ülke": [
                "{name} hangi ülke adına ter dökmektedir?",
                "{name} hangi ülkenin sporcusudur?",
                "{name} hangi ülkenin sporcusu?",
                "{name} hangi ülke adına yarışmaktadır?",
                "{name}'{~}n doğduğu yer"
            ],
            "spor": [
                "{name} hangi spor dalındadır?",
                "{name} hangi spor dalında mücadele etmektedir?",
                "{name} hangi sporu yapar?"
            ],
            "uyruk": [
                "{name} nerelidir?",
                "{name} hangi ülke asıllıdır?",
                "{name} hangi millettendir?",
                "{name}'{~}n hangi millettendir?"
            ],
            "kei": [
                "{name}'{~}n en iyi derecesi nedir?",
                "{name}'{~}n en iyi derecesi ne"
            ],
            "ağırlık": [

            ]
        },
        "Tenis sporcu": {
            "doğumyeri": [
                "{name} nerede doğmuştur?",
                "{name} nerede doğdu",
                "{name} doğum yeri",
                "{name}'{~}n doğum yeri",
                "{name} doğum yeri neresi",
                "{name}'{~}n doğum yeri neresi",
                "{name}'{~}n doğum yeri neresidir",
                "{name} doğum yeri neresidir",
                "{name} nereli",
                "{name} memleketi",
                "{name}'{~}n memleketi",
                "{name} memleketi nedir",
                "{name}'{~}n memleketi nedir",
                "{name} doğduğu yer",
                "{name}'{~}n doğduğu yer",
                "{name} doğduğu yer neresidir",
                "{name}'{~}n doğduğu yer neresidir",
                "{name} doğduğu yer neresi",
                "{name}'{~}n doğduğu yer neresi",
                "{name} doğduğu il",
                "{name}'{~}n doğduğu il",
                "{name} hangi ilde doğdu",
                "{name} hangi ülkede doğdu",
                "{name} doğduğu ülke",
                "{name}'{~}n doğduğu ülke"
            ],
            "vatandaşlık": [

            ],
            "enyükseksıralama": [

            ],
            "oyunstili": [

            ],
            "wimbledonsonuçları": [
                "{name}'{~}n Amerika açık sonuçları nedir?",
                "{name}'{~}n Amerika açık sonuçları nelerdir?",
                "{name}'{~}n Amerika açık sonuçları nasıl?"
            ],
            "amerikaaçıksonuçları": [
                "{name}'{~}n Amerika açık sonuçları nedir?",
                "{name}'{~}n Amerika açık sonuçları nelerdir?",
                "{name}'{~}n Amerika açık sonuçları nasıl?"
            ],
            "fransaaçıksonuçları": [
                "{name}'{~}n Fransa açık sonuçları nedir?",
                "{name}'{~}n Fransa açık sonuçları nelerdir?",
                "{name}'{~}n Fransa açık sonuçları nasıl?"
            ],
            "avustralyaaçıksonuçları": [
                "{name}'{~}n Avustralya açık sonuçları nedir?",
                "{name}'{~}n Avustralya açık sonuçları nelerdir?",
                "{name}'{~}n Avustralya açık sonuçları nasıl?"
            ],
            "toplamkupa": [
                
            ],
            "yaşadığıyer": [

            ]
        },
        "Voleybolcu": {
            "doğumtarihi": [
                "{name}'{~}n doğum tarihi",
                "{name}'{~}n doğum tarihi nedir?",
                "{name}'{~}n doğum tarihi ne zaman",
                "{name}'{~}n doğum yılı",
                "{name}'{~}n doğum yılı nedir",
                "{name}'{~}n doğum yılı ne zaman",
                "{name}'{~}n doğum günü ne zaman",
                "{name}'{~}n doğum günü nedir",
                "{name} doğum tarihi",
                "{name} doğum tarihi nedir",
                "{name} doğum tarihi ne zaman",
                "{name} doğum yılı",
                "{name} doğum yılı nedir",
                "{name} doğum yılı ne zaman",
                "{name} doğum günü ne zaman",
                "{name} doğum günü nedir",
                "{name} ne zaman doğmuştur?",
                "{name} ne zaman doğdu",
                "{name} doğum zamanı"
            ],
            "doğumyeri": [
                "{name} nerede doğmuştur?",
                "{name} nerede doğdu",
                "{name} doğum yeri",
                "{name}'{~}n doğum yeri",
                "{name} doğum yeri neresi",
                "{name}'{~}n doğum yeri neresi",
                "{name}'{~}n doğum yeri neresidir",
                "{name} doğum yeri neresidir",
                "{name} nereli",
                "{name} memleketi",
                "{name}'{~}n memleketi",
                "{name} memleketi nedir",
                "{name}'{~}n memleketi nedir",
                "{name} doğduğu yer",
                "{name}'{~}n doğduğu yer",
                "{name} doğduğu yer neresidir",
                "{name}'{~}n doğduğu yer neresidir",
                "{name} doğduğu yer neresi",
                "{name}'{~}n doğduğu yer neresi",
                "{name} doğduğu il",
                "{name}'{~}n doğduğu il",
                "{name} hangi ilde doğdu",
                "{name} hangi ülkede doğdu",
                "{name} doğduğu ülke",
                "{name}'{~}n doğduğu ülke"
            ],
            "pozisyon": [
                "{name} hangi pozisyonda oynamaktadır?",
                "{name} hangi pozisyonda oynar?",
                "{name} hangi pozisyonda oynuyor?",
                "{name} hangi mevkiide oynamaktadır?",
                "{name} hangi mevkiide oynar?",
                "{name} hangi mevkiide oynuyor?",
                "{name}'{~}n oynadığı pozisyon nedir?",
                "{name}'{~}n oynamakta olduğu pozisyon nedir?",
                "{name}'{~}n pozisyonu nedir?",
                "{name}'{~}n oyun pozisyonu nedir?",
                "{name}'{~}n maçlardaki pozisyonu nedir?"
            ],
            "milliyeti": [
                "{name} nerelidir?",
                "{name} hangi ülke asıllıdır?",
                "{name} hangi millettendir?",
                "{name}'{~}n hangi millettendir?"
            ],
            "kulüpyıl": [

            ],
            "kulüptakım": [
                "{name} hangi takımlarda oynamıştır?",
                "{name} hangi takımlarda oynamıştı?",
                "{name} hangi takımlarda oynamıştır?",
                "{name} hangi takımlarda oynamıştır?",

            ],
            "bulunduğukulüp": [
                "{name} hangi takımda oynamaktadır?",
                "{name} şu an hangi takımda oynamaktadır?",
                "{name} hangi takımda oynuyor?",
                "{name} şu an hangi takımda oynuyor?",
                "{name} hangi takımın oyuncusudur?",
                "{name} şu an hangi takımın oyuncusudur?",
                "{name} hangi takımdadır?",
                "{name} şu an hangi takımdadır?",
                "{name}'{~}n oynadığı takım hangisidir?",
                "{name}'{~}n takımı hangisidir?",
                "{name}'{~}n güncel takımı hangisidir?",
                "{name}'{~}n şu an oynadığı takım hangisidir?"
            ],
            "numarası": [
                "{name}'{~}n forma numarası nedir?",
                "{name}'{~}n forması kaç numara?",
                "{name}'{~}n forması kaç numaradır?",
                "{name}'{~}n forması kaç numaraydı?",
                "{name} kaç numaralı formayı giymektedir?",
                "{name} kaç numaralı formayı giymişti?",
                "{name} hangi forma numarasına sahiptir?",
                "{name} sahip olduğu forma numarası nedir?"
            ],
            "millitakım": [
                "{name} hangi milli takımda oynamaktadır?",
                "{name} hangi milli takımda oynuyor?",
                "{name} hangi milli takımda oynamakta?",
                "{name} hangi ülkenin milli takımında oynamaktadır?",
                "{name} hangi ülkenin milli takımında oynadı?",
                "{name} oynadığı milli takım hangisidir?",
                "{name}'{~}n oynadığı milli takım hangisidir?",
                "{name} oynadığı milli takım hangisi?",
                "{name}'{~}n oynadığı milli takım hangisi?",
                "{name} oynadığı milli takım nedir?",
                "{name}'{~}n oynadığı milli takım nedir?",
                "{name} nerenin milli takımında oynamaktadır?",
                "{name} nerenin milli takımında oynamıştı?",
                "{name} nerenin milli takımında oynuyor?",
                "{name} nerenin milli takımında oynadı?"
            ],
            "milliyıl": [

            ]

        },
        "Yazar": {
            "doğumyeri": [
                "{name} nerede doğmuştur?",
                "{name} nerede doğdu",
                "{name} doğum yeri",
                "{name}'{~}n doğum yeri",
                "{name} doğum yeri neresi",
                "{name}'{~}n doğum yeri neresi",
                "{name}'{~}n doğum yeri neresidir",
                "{name} doğum yeri neresidir",
                "{name} nereli",
                "{name} memleketi",
                "{name}'{~}n memleketi",
                "{name} memleketi nedir",
                "{name}'{~}n memleketi nedir",
                "{name} doğduğu yer",
                "{name}'{~}n doğduğu yer",
                "{name} doğduğu yer neresidir",
                "{name}'{~}n doğduğu yer neresidir",
                "{name} doğduğu yer neresi",
                "{name}'{~}n doğduğu yer neresi",
                "{name} doğduğu il",
                "{name}'{~}n doğduğu il",
                "{name} hangi ilde doğdu",
                "{name} hangi ülkede doğdu",
                "{name} doğduğu ülke",
                "{name}'{~}n doğduğu ülke"
            ],
            "meslek": [
                "{name}'{~}n mesleği",
                "{name}'{~}n mesleği ne",
                "{name}'{~}n mesleği neydi",
                "{name}'{~}n gerçek mesleği",
                "{name}'{~}n gerçek mesleği nedir?",
                "{name}'{~}n gerçek mesleği neydi",
                "{name}'{~}n mesleği nedir?",
                "{name} mesleği nedir?",
                "{name} mesleği ne idi?",
                "{name} hangi mesleğe mensuptur?",
                "{name} hangi mesleğe mensup?",
                "{name} hangi mesleği yapıyordu?",
                "{name} hangi işi yapıyor?",
                "{name} hangi işi yapıyordu?"
            ],
            "doğumtarihi": [
                "{name}'{~}n doğum tarihi",
                "{name}'{~}n doğum tarihi nedir?",
                "{name}'{~}n doğum tarihi ne zaman",
                "{name}'{~}n doğum yılı",
                "{name}'{~}n doğum yılı nedir",
                "{name}'{~}n doğum yılı ne zaman",
                "{name}'{~}n doğum günü ne zaman",
                "{name}'{~}n doğum günü nedir",
                "{name} doğum tarihi",
                "{name} doğum tarihi nedir",
                "{name} doğum tarihi ne zaman",
                "{name} doğum yılı",
                "{name} doğum yılı nedir",
                "{name} doğum yılı ne zaman",
                "{name} doğum günü ne zaman",
                "{name} doğum günü nedir",
                "{name} ne zaman doğmuştur?",
                "{name} ne zaman doğdu",
                "{name} doğum zamanı"
            ],
            "ölümtarihi": [
                "{name}'{~}n ölüm tarihi",
                "{name}'{~}n ölüm tarihi nedir",
                "{name}'{~}n ölüm tarihi ne zaman",
                "{name}'{~}n ölüm yılı",
                "{name}'{~}n ölüm yılı nedir",
                "{name}'{~}n ölüm yılı ne zaman",
                "{name}'{~}n ölüm günü ne zaman",
                "{name}'{~}n ölüm günü nedir",
                "{name} ölüm tarihi",
                "{name} ölüm tarihi nedir",
                "{name} ölüm tarihi ne zaman",
                "{name} ölüm yılı",
                "{name} ölüm yılı nedir",
                "{name} ölüm yılı ne zaman",
                "{name} ölüm günü ne zaman",
                "{name} ölüm günü nedir",
                "{name} ne zaman ölmüştür",
                "{name} ne zaman ölüm",
                "{name} ölüm zamanı",
                "{name}'{~}n ölüm zamanı"
            ],
            "ölümyeri": [
                "{name} nerede ölmüştür",
                "{name} nerede öldü",
                "{name} ölüm yeri",
                "{name}'{~}n ölüm yeri",
                "{name} ölüm yeri neresi",
                "{name}'{~}n ölüm yeri neresi",
                "{name}'{~}n ölüm yeri neresidir",
                "{name} ölüm yeri neresidir",
                "{name} öldüğü yer",
                "{name}'{~}n öldüğü yer",
                "{name} öldüğü yer neresidir",
                "{name}'{~}n öldüğü yer neresidir",
                "{name} öldüğü yer neresi",
                "{name}'{~}n ölüdüğü yer neresi",
                "{name} doğduğu il",
                "{name}'{~}n ölüdüğü il",
                "{name} hangi ilde öldü",
                "{name} hangi ülkede öldü",
                "{name} öldüğü ülke",
                "{name}'{~}n öldüğü ülke"
            ],
            "tür": [
                "{name} hangi türde eser vermiştir?",
                "{name} hangi türde eserler vermiştir?",
                "{name} hangi türde yazmıştır?",
                "{name} hangi türde yazmaktaydır?",
                "{name}'{~}n eserleri hangi türdedir?",
                "{name}'{~}n eser türleri?",
                "{name}'{~}n eserleri hangi türdedir?",
                "{name}'{~}n eserleri hangi türdeydi?",
                "{name}'{~}n eser türü nedir?"
            ],
            "dönem": [
                "{name} hangi dönemde eser vermiştir?",
                "{name} hangi dönemde eserler vermiştir?",
                "{name} hangi dönem yazarıdır?",
                "{name} eser verdiği dönem nedir?",
                "{name} eser verdiği dönem hangisidir?"
            ],
            "ilkeser": [
                "{name}'{~}n ilk eseri nedir?",
                "{name}'{~}n ilk eseri hangisidir?",
                "{name}'{~}n ilk eseri?",
                "{name}'{~}n ilk eserinin adı nedir?",
                "{name}'{~}n verdiği ilk eserinin adı nedir?",
                "{name}'{~}n verdiği ilk eseri nedir?",
                "{name}'{~}n verdiği ilk eseri hangisidir?"
            ]
        }
    }
