class QuestionPatterns:
    patterns = {
        "Asker": {
            "rütbesi": [
                "{name} hangi rütbede görev yapmaktaydı?",
                "{name}'{~}n rütbesi nedir?",
                "{name}'{~}n rütbesi",
                "{name}'{~}n rütbesi neydi?",
                "{name} rütbe",
                "{name} hangi rütbe"
            ],
            "doğumyeri": [
                "{name} nerede doğmuştur?",
                "{name} nerede doğdu",
                "{name} doğum yeri",
                "{name}'{~}n doğum yeri",
                "{name} doğum yeri neresi",
                "{name}'{~}n doğum yeri neresi",
                "{name}'{~}n doğum yeri neresidir",
                "{name} doğum yeri neresidir",
                "{name} nereli",
                "{name} memleketi",
                "{name}'{~}n memleketi",
                "{name} memleketi nedir",
                "{name}'{~}n memleketi nedir",
                "{name} doğduğu yer",
                "{name}'{~}n doğduğu yer",
                "{name} doğduğu yer neresidir",
                "{name}'{~}n doğduğu yer neresidir",
                "{name} doğduğu yer neresi",
                "{name}'{~}n doğduğu yer neresi",
                "{name} doğduğu il",
                "{name}'{~}n doğduğu il",
                "{name} hangi ilde doğdu",
                "{name} hangi ülkede doğdu",
                "{name} doğduğu ülke",
                "{name}'{~}n doğduğu ülke",
            ],
            "doğumtarihi": [
                "{name}'{~}n doğum tarihi",
                "{name}'{~}n doğum tarihi nedir",
                "{name}'{~}n doğum tarihi ne zaman",
                "{name}'{~}n doğum yılı",
                "{name}'{~}n doğum yılı nedir",
                "{name}'{~}n doğum yılı ne zaman",
                "{name}'{~}n doğum günü ne zaman",
                "{name}'{~}n doğum günü nedir",
                "{name} doğum tarihi",
                "{name} doğum tarihi nedir",
                "{name} doğum tarihi ne zaman",
                "{name} doğum yılı",
                "{name} doğum yılı nedir",
                "{name} doğum yılı ne zaman",
                "{name} doğum günü ne zaman",
                "{name} doğum günü nedir",
                "{name} ne zaman doğmuştur",
                "{name} ne zaman doğdu",
                "{name} doğum zamanı",
            ],
            "hizmetyılları": [
                "{name}'{~}n hizmet yılları",
                "{name}'{~}n hizmet yılları nedir",
                "{name}'{~}n hizmet yılları ne zaman",
                "{name}'{~}n hizmet yılları ne zamandır",
                "{name}'{~}n ordudaki yılları",
                "{name}'{~}n ordudaki yılları nedir",
                "{name}'{~}n orduda geçirdiği yılları",
                "{name}'{~}n orduda geçirdiği yıllar",
                "{name} hizmet yılları",
                "{name} hizmet yılları nedir",
                "{name} hizmet yılları ne zaman",
                "{name} hizmet yılları ne zamandır",
                "{name} ordudaki yılları",
                "{name} ordudaki yılları nedir",
                "{name} orduda geçirdiği yılları",
                "{name} orduda geçirdiği yıllar",
                "{name} ne zaman hizmet vermiştir",
                "{name} ne zamanlar hizmet vermiştir",
                "{name} ne zaman hizmet vermişti",
                "{name} ne zamanlar hizmet vermişti",
                "{name} ne zaman askerdi",
                "{name} ne zaman asker olarak görev yapmıştır",
                "{name} ne zaman hizmet vermiştir",
                "{name} orduda geçirdiği yıllar",
                "{name} hangi yıllarını orduda geçirdi",
                "{name} hangi yıllarda ordudaydı",
                "{name} hangi yıllarda askerdi",
                "{name} hangi yıllarda arasında askerdi",
                "{name} hizmet dönemi",
                "{name} askerlik dönemi",
                "{name} ordu dönemi",
                "{name} ordudaki dönemi",
                "{name} ne zaman ordudaydı",
            ],
            "bağlılığı": [
                "{name} hangi ordudaydı",
                "{name} hangi orduda görev aldı",
                "{name} hangi orduya bağlı",
                "{name} hangi orduya bağlıydı",
                "{name} hangi orduya bağlıdır",
                "{name} hangi orduya bağlı görev aldı",
                "{name} hangi orduya bağlı görev almıştır",
                "{name} hangi ülke ordusundadır",
                "{name} hangi ülke ordusundaydı",
                "{name} hangi ülkenin ordusundaydı",
            ],
            "ölümyeri": [
                "{name} nerede ölmüştür",
                "{name} nerede öldü",
                "{name} ölüm yeri",
                "{name}'{~}n ölüm yeri",
                "{name} ölüm yeri neresi",
                "{name}'{~}n ölüm yeri neresi",
                "{name}'{~}n ölüm yeri neresidir",
                "{name} ölüm yeri neresidir",
                "{name} öldüğü yer",
                "{name}'{~}n öldüğü yer",
                "{name} öldüğü yer neresidir",
                "{name}'{~}n öldüğü yer neresidir",
                "{name} öldüğü yer neresi",
                "{name}'{~}n ölüdüğü yer neresi",
                "{name} doğduğu il",
                "{name}'{~}n ölüdüğü il",
                "{name} hangi ilde öldü",
                "{name} hangi ülkede öldü",
                "{name} öldüğü ülke",
                "{name}'{~}n öldüğü ülke",
            ],
            "savaşları": [
                "{name} nerede savaştı",
                "{name} nerelerde savaştı",
                "{name} hangi cephelerde savaştı",
                "{name} hangi savaşlarda savaştı",
                "{name} hangi savaşlarda vardı",
                "{name} hangi savaşlardaydı",
                "{name} hangi savaşlara katıldı",
                "{name}'{~}n katıldığı savaşlar",
                "{name} katıldığı savaşlar",
                "{name} bulunduğu savaşlar",
                "{name}'{~}n bulunduğu savaşlar",
                "{name} savaşlar",
                "{name}'{~}n savaşlar",
                "{name} savaşları",
                "{name}'{~}n savaşları",
                "{name} savaştığı yerler",
                "{name}'{~}n savaştığı yerler",
                "{name}'{~}n savaştığı yerler neresi",
                "{name}'{~}n savaştığı yerler hangiler",
                "{name}'{~}n savaştığı yerler hangileridir",
                "{name}'{~}n savaştığı yerler hangileriydi",
                "{name}'{~}n savaştığı yer hangileriydi",
                "{name}'{~}n savaştığı yer hangileri",
            ],
            "ölümtarihi": [
                "{name}'{~}n ölüm tarihi",
                "{name}'{~}n ölüm tarihi nedir",
                "{name}'{~}n ölüm tarihi ne zaman",
                "{name}'{~}n ölüm yılı",
                "{name}'{~}n ölüm yılı nedir",
                "{name}'{~}n ölüm yılı ne zaman",
                "{name}'{~}n ölüm günü ne zaman",
                "{name}'{~}n ölüm günü nedir",
                "{name} ölüm tarihi",
                "{name} ölüm tarihi nedir",
                "{name} ölüm tarihi ne zaman",
                "{name} ölüm yılı",
                "{name} ölüm yılı nedir",
                "{name} ölüm yılı ne zaman",
                "{name} ölüm günü ne zaman",
                "{name} ölüm günü nedir",
                "{name} ne zaman ölmüştür",
                "{name} ne zaman ölüm",
                "{name} ölüm zamanı",
                "{name}'{~}n ölüm zamanı",
            ],
            "komutaettikleri": [
                "{name}'{~}n komuta ettikleri",
                "{name} komuta ettikleri",
                "{name} kimleri komuta etti",
                "{name} kimleri komuta etmiştir",
                "{name} altındaki askerler"
                "{name} komuta altındaki askerler"
                "{name}'{~}n komutası altındaki askerler"
                "{name} altındaki askerler"
                "",
            ],
        },
         "Basketbolcu": {},
         "Bilim adamı": {},
         "Bilim insanı": {},
         "Buz patencisi": {},
         "Filozof": {},
         "Futbolcu": {},
         "Güreşçi": {},
         "Hakem": {},
         "Kişi": {},
         "Kraliyet": {},
         "Makam sahibi": {},
         "Manken": {},
         "Müzik sanatçısı": {},
         "Oyuncu": {},
         "Profesyonel güreşçi": {},
         "Sanatçı": {},
         "Sporcu": {},
         "Tenis sporcu": {},
         "Voleybolcu": {
             "doğumtarihi": [
                "{name}'{~}n doğum tarihi",
                "{name}'{~}n doğum tarihi nedir?",
                "{name}'{~}n doğum tarihi ne zaman",
                "{name}'{~}n doğum yılı",
                "{name}'{~}n doğum yılı nedir",
                "{name}'{~}n doğum yılı ne zaman",
                "{name}'{~}n doğum günü ne zaman",
                "{name}'{~}n doğum günü nedir",
                "{name} doğum tarihi",
                "{name} doğum tarihi nedir",
                "{name} doğum tarihi ne zaman",
                "{name} doğum yılı",
                "{name} doğum yılı nedir",
                "{name} doğum yılı ne zaman",
                "{name} doğum günü ne zaman",
                "{name} doğum günü nedir",
                "{name} ne zaman doğmuştur?",
                "{name} ne zaman doğdu",
                "{name} doğum zamanı",
            ],
            "doğumyeri": [
                "{name} nerede doğmuştur?",
                "{name} nerede doğdu",
                "{name} doğum yeri",
                "{name}'{~}n doğum yeri",
                "{name} doğum yeri neresi",
                "{name}'{~}n doğum yeri neresi",
                "{name}'{~}n doğum yeri neresidir",
                "{name} doğum yeri neresidir",
                "{name} nereli",
                "{name} memleketi",
                "{name}'{~}n memleketi",
                "{name} memleketi nedir",
                "{name}'{~}n memleketi nedir",
                "{name} doğduğu yer",
                "{name}'{~}n doğduğu yer",
                "{name} doğduğu yer neresidir",
                "{name}'{~}n doğduğu yer neresidir",
                "{name} doğduğu yer neresi",
                "{name}'{~}n doğduğu yer neresi",
                "{name} doğduğu il",
                "{name}'{~}n doğduğu il",
                "{name} hangi ilde doğdu",
                "{name} hangi ülkede doğdu",
                "{name} doğduğu ülke",
                "{name}'{~}n doğduğu ülke",
            ],
            "pozisyon": [
                
            ],
            "milliyeti": [
                
            ],
            "kulüpyıl": [
                
            ],
            "kulüptakım": [
                
            ],
            "bulunduğukulüp": [
                
            ],
            "numarası": [
                
            ],
            "millitakım": [
                
            ],
            "milliyıl": [
                
            ]

         },
         "Yazar": {
             "doğumyeri": [
                "{name} nerede doğmuştur?",
                "{name} nerede doğdu",
                "{name} doğum yeri",
                "{name}'{~}n doğum yeri",
                "{name} doğum yeri neresi",
                "{name}'{~}n doğum yeri neresi",
                "{name}'{~}n doğum yeri neresidir",
                "{name} doğum yeri neresidir",
                "{name} nereli",
                "{name} memleketi",
                "{name}'{~}n memleketi",
                "{name} memleketi nedir",
                "{name}'{~}n memleketi nedir",
                "{name} doğduğu yer",
                "{name}'{~}n doğduğu yer",
                "{name} doğduğu yer neresidir",
                "{name}'{~}n doğduğu yer neresidir",
                "{name} doğduğu yer neresi",
                "{name}'{~}n doğduğu yer neresi",
                "{name} doğduğu il",
                "{name}'{~}n doğduğu il",
                "{name} hangi ilde doğdu",
                "{name} hangi ülkede doğdu",
                "{name} doğduğu ülke",
                "{name}'{~}n doğduğu ülke",
            ],
            "meslek": [

            ]
             "doğumtarihi": [
                "{name}'{~}n doğum tarihi",
                "{name}'{~}n doğum tarihi nedir?",
                "{name}'{~}n doğum tarihi ne zaman",
                "{name}'{~}n doğum yılı",
                "{name}'{~}n doğum yılı nedir",
                "{name}'{~}n doğum yılı ne zaman",
                "{name}'{~}n doğum günü ne zaman",
                "{name}'{~}n doğum günü nedir",
                "{name} doğum tarihi",
                "{name} doğum tarihi nedir",
                "{name} doğum tarihi ne zaman",
                "{name} doğum yılı",
                "{name} doğum yılı nedir",
                "{name} doğum yılı ne zaman",
                "{name} doğum günü ne zaman",
                "{name} doğum günü nedir",
                "{name} ne zaman doğmuştur?",
                "{name} ne zaman doğdu",
                "{name} doğum zamanı",
            ],
            "ölümtarihi": [
                "{name}'{~}n ölüm tarihi",
                "{name}'{~}n ölüm tarihi nedir",
                "{name}'{~}n ölüm tarihi ne zaman",
                "{name}'{~}n ölüm yılı",
                "{name}'{~}n ölüm yılı nedir",
                "{name}'{~}n ölüm yılı ne zaman",
                "{name}'{~}n ölüm günü ne zaman",
                "{name}'{~}n ölüm günü nedir",
                "{name} ölüm tarihi",
                "{name} ölüm tarihi nedir",
                "{name} ölüm tarihi ne zaman",
                "{name} ölüm yılı",
                "{name} ölüm yılı nedir",
                "{name} ölüm yılı ne zaman",
                "{name} ölüm günü ne zaman",
                "{name} ölüm günü nedir",
                "{name} ne zaman ölmüştür",
                "{name} ne zaman ölüm",
                "{name} ölüm zamanı",
                "{name}'{~}n ölüm zamanı",
            ],
            "ölümyeri": [
                "{name} nerede ölmüştür",
                "{name} nerede öldü",
                "{name} ölüm yeri",
                "{name}'{~}n ölüm yeri",
                "{name} ölüm yeri neresi",
                "{name}'{~}n ölüm yeri neresi",
                "{name}'{~}n ölüm yeri neresidir",
                "{name} ölüm yeri neresidir",
                "{name} öldüğü yer",
                "{name}'{~}n öldüğü yer",
                "{name} öldüğü yer neresidir",
                "{name}'{~}n öldüğü yer neresidir",
                "{name} öldüğü yer neresi",
                "{name}'{~}n ölüdüğü yer neresi",
                "{name} doğduğu il",
                "{name}'{~}n ölüdüğü il",
                "{name} hangi ilde öldü",
                "{name} hangi ülkede öldü",
                "{name} öldüğü ülke",
                "{name}'{~}n öldüğü ülke",
            ],
            "başlık": [

            ],
            "tür": [
                
            ],
            "dönem": [
                
            ],
            "ilkeser": [
                
            ]
         }
    }